
version: '3.9'

services:
  web:
    build: .
    container_name: my-web
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - my-network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: my-db
    restart: always
    environment:
      MYSQL_DATABASE: toystore
      MYSQL_USER: phuctd
      MYSQL_PASSWORD: tranducphuc2003
      MYSQL_ROOT_PASSWORD: Tranducphuc2003
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-dbadmin
    environment:
      PMA_HOST: db
      #PMA_USER: db_user
      #PMA_PASSWORD: dbPass@123
    ports:
      - "8080:80"
    restart: always
    networks:
      - my-network
    depends_on:
      - db

networks:
  my-network: